title: webcook tech
email: chefboy@naver.com
author: Dinosaur Avocado
description: >
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ""
url: "https://webcook.github.io"
repo: "https://github.com/webcook/"
github_user: webcook
github_repo: webcook.github.io
github_branch: master
twitter: none
linkedin: none
dockerhub: none
feedback: true
logo_pixels: 34
color: "#30638e"
markdown: kramdown
tag_color: primary
accentColor: red
themeColor: red
fixedNav: "true"
permalink: "/:year/:title/"
exclude:
  - _site
  - CHANGELOG.md
  - LICENSE
  - README.md
  - vendor
collections:
  docs:
    output: true
    permalink: "/:collection/:path"
defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: page
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: posts
      type: posts
    values:
      layout: post
